#!/usr/bin/env bash
# Install and  the load balancer
apt-get update -y
apt-get install -y haproxy

CONF="\
frontend main
	 bind *:80
	 mode http
	 default_backend web-server
backend web-server
	balance roundrobin
	server 1235-web-01 34.74.176.42 check
	server 1235-web-02 34.75.43.152 check
"

echo "$CONF" >> /etc/haproxy/haproxy.cfg
echo "ENABLED=1" >> /etc/default/haproxy
service haproxy start
