#!/usr/bin/env bash
# display messages with SIGTERM and SIGINT
echo $$ > /var/run/holbertonscript.pid
while ((1))
do
    echo "To infinity and beyond"
    trap "echo Y U no love me?!" 2
    trap "echo I hate the kill command; sudo rm /var/run/holbertonscript.pid" 3 15
done
