#!/usr/bin/env bash
# Fizz Buzz
x=1
while [ $x -le 101 ]
do
	if [ $((x % 5)) == 0 -a $((x % 3)) == 0 ]
    then
		echo "FizzBuzz"
	elif [ $((x % 5)) == 0 ]
    then
		echo "Buzz"
	elif [ $((x % 3)) == 0 ]
    then
		echo "Fizz"
	else
		echo $x
	fi
    x=$(( x + 1 ))
done
