#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times and 9 times "Hi"
x=1
while [ $x -le 10 ]
do
	echo "Holberton School"
	if [ $x = 9 ]
	then
		echo "Hi"
	fi
  		x=$(( x + 1 ))
done
