#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
x=1
while [ $x -le 20 ]
do
  echo "$x"
  case $x in
  	17)
  	echo "bad lucky from Italy"
  ;;
  	9)
  	echo "bad lucky from Japan"
  ;;
  	4)
  	echo "bad lucky from China"
  ;;
  esac
:	$(( x++ ))
done
