#!/usr/bin/env bash
# This script is displaying 20 times bad lucky
x=1
while [ $x -le 20 ]
do
  echo "$x"
  case $x in
  	17)
  	echo "bad lucky from Italy"
  	;;
  	9)
  	echo "bad lucky from Japan"
  	;;
  	4)
  	echo "bad lucky from China"
  	;;
	esac
	x=$(( x + 1))
done
